// Available pages on Sidebar Menu

const HOME = "HOME";
const SEARCH = "SEARCH";
const YOUR_LIBRARY = "YOUR_LIBRARY"
const CREATE_PLAYLIST = "CREATE_PLAYLIST"
const YOUR_EPISODES = "YOUR_EPISODES"
const LIKED_SONGS = "LIKED_SONGS";
const PLAYLIST = "PLAYLIST";

export { HOME, SEARCH, YOUR_LIBRARY, CREATE_PLAYLIST, YOUR_EPISODES, LIKED_SONGS, PLAYLIST }